version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: picnest-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: picnest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - picnest-network

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: picnest-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - picnest-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  picnest-network:
    driver: bridge
